# Generated by Django 5.2.10 on 2026-06-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activityparticipant_status'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbill',
            name='bill_type',
            field=models.CharField(choices=[('kas', 'Kas'), ('iuran', 'Iuran')], default='kas', max_length=20),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='fee_type',
            field=models.CharField(choices=[('kas', 'Kas Bulanan'), ('iuran', 'Iuran')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Belum Bayar'), ('paid', 'Lunas')], default='unpaid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='activity.activityparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='activity_fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.activityfine'),
        ),
    ]
