# Generated by Django 5.2.10 on 2026-02-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('sebelum', models.IntegerField()),
                ('ditambah', models.IntegerField()),
                ('digunakan', models.IntegerField()),
                ('sisa', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FotoInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_inventory/')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventory.inventory')),
            ],
        ),
    ]
