# Generated by Django 5.2.10 on 2026-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='digunakan',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sisa',
        ),
        migrations.AddField(
            model_name='inventory',
            name='dipakai',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='habis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rusak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tipe',
            field=models.CharField(choices=[('consumable', 'Habis Pakai'), ('asset', 'Aset')], default='asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ditambah',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sebelum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
