# Generated by Django 5.2.10 on 2026-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_digunakan_remove_inventory_sisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tipe',
            field=models.CharField(choices=[('consumable', 'Habis'), ('asset', 'Aset')], default='asset', max_length=20),
        ),
    ]
