# Generated by Django 5.2.10 on 2026-02-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tipe', models.CharField(choices=[('kegiatan', 'Kegiatan'), ('acara', 'Acara')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('gdrive_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('absen', 'Absen'), ('izin', 'Izin')], default='hadir', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, help_text='Jika peserta adalah unit/departemen, isi field ini', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='organization.organizationunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participants', to='activity.event')),
            ],
            options={
                'verbose_name': 'Activity Participant',
                'verbose_name_plural': 'Activity Participants',
                'indexes': [models.Index(fields=['event', 'status'], name='activity_ac_event_i_7a9a3a_idx'), models.Index(fields=['user', 'status'], name='activity_ac_user_id_044da5_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activity.event')),
                ('role', models.ForeignKey(blank=True, help_text='Peran dalam panitia: Ketua, Sekretaris, Bendahara, dll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participants', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
