# Generated by Django 5.2.10 on 2026-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('absen', 'Absen'), ('sakit', 'Sakit'), ('izin', 'Izin')], default='hadir', max_length=20),
        ),
    ]
