# Generated by Django 5.2.10 on 2026-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('masuk', 'Surat Masuk'), ('keluar', 'Surat Keluar')], max_length=10)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('pengirim', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='surat/')),
            ],
        ),
    ]
